// Auto-generated game translations map — regenerated by scripts/sync-game-i18n.mjs
// DO NOT EDIT MANUALLY

const enGames = {
  "breakout": {
    "title": "Breakout",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "bubble-pop": {
    "title": "Bubble Pop",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "checkers": {
    "title": "Checkers",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "chess": {
    "title": "Chess",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "chronoshift": {
    "title": "ChronoShift Labyrinth",
    "score": "Score",
    "rewinds": "Rewinds",
    "crystals": "Crystals",
    "rewinding": "Rewinding...",
    "controls": "WASD/Arrows: Move  |  R: Rewind  |  E: Shift Wall",
    "win": "Maze Complete!",
    "lose": "Game Over",
    "finalScore": "Final Score",
    "playAgain": "Play Again"
  },
  "timeclone": {
    "title": "Time Clone Puzzle",
    "score": "Score",
    "level": "Level",
    "phase": "Phase",
    "explore": "Explore",
    "recording": "Recording moves",
    "cloneActive": "Clone active",
    "controls": "WASD/Arrows: Move | Reach time-gate to record | Clone repeats your path",
    "win": "Temporal Harmony Achieved!",
    "finalScore": "Final Score",
    "retry": "Retry",
    "nextLevel": "Next Puzzle",
    "playAgain": "Play Again",
    "you": "You",
    "clone": "Time Clone",
    "yourExit": "Your Exit",
    "cloneExit": "Clone Exit",
    "timegate": "Time Gate",
    "switch": "Switch Tile"
  },
  "elementalconflux": {
    "title": "Elemental Conflux",
    "fire": "Fire",
    "water": "Water",
    "earth": "Earth",
    "air": "Air",
    "fAbility": "Melt Ice",
    "qAbility": "Douse Fire",
    "gAbility": "Pillar",
    "spaceAbility": "Push",
    "active": "active",
    "controls": "WASD/Arrows: Move | Tab/1-4: Switch | F: Fire | Q: Water | G: Earth | Space: Air",
    "level": "Level",
    "moves": "Moves",
    "time": "Time",
    "complete": "All Elements United!",
    "reached": "Reached",
    "pending": "Pending",
    "finalScore": "Score",
    "restart": "Restart",
    "nextLevel": "Next Level",
    "playAgain": "Play Again"
  },
  "memory": {
    "title": "Memory",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "platformer": {
    "title": "Puzzle Platformer",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "quantumarchitect": {
    "title": "Quantum Architect",
    "score": "Score",
    "observations": "Observations",
    "quantumProb": "Probability:",
    "controls": "WASD/Arrows to move | Space to observe | Collect keys to open gates",
    "begin": "Begin Experiment",
    "level": "Level",
    "win": "Wave Function Resolved!",
    "finalScore": "Final Score",
    "totalObs": "Total Observations",
    "newExperiment": "New Experiment",
    "subtitle": "Manipulate quantum states, collect keys, and navigate entangled platforms.",
    "keys": "Keys",
    "gateLocked": "Locked",
    "gateOpen": "Open",
    "entangled": "Entangled",
    "bias": "Bias"
  },
  "rod": {
    "intro": {
      "title": "Rite of Discovery — Intro",
      "p1": "A family tradition. A quiet choice. Tonight it begins.",
      "p2": "Pay attention to details — they might guide your choices.",
      "cta": "Begin",
      "skip": "Skip intro"
    },
    "hallway": {
      "title": "The Dim Hallway",
      "body": "A heavy metal door blocks your path. A keypad glows faintly.",
      "goBack": "Go back"
    },
    "keypad": {
      "title": "Keypad Lock",
      "body": "Enter the 4-digit code found on the old parchment.",
      "back": "Back",
      "input": "Input:",
      "clear": "Clear",
      "submit": "Submit",
      "unlocked": "Unlocked"
    },
    "wires": {
      "title": "Maintenance Panel",
      "body": "Exposed wires hum with power. Connect them correctly to restore light.",
      "back": "Back",
      "solved": "Wires: Solved",
      "connect": "Connect"
    },
    "chamber": {
      "title": "The Inner Chamber",
      "body": "The air is still here. You've passed the first trial.",
      "restart": "Restart"
    },
    "s1": {
      "title": "Night Before",
      "body": "The living room is quiet. Wrapping paper and tags are scattered on the table. One tag has torn apart — reassemble it.",
      "prompt": "Assemble the magic tags in the correct order:",
      "tags": {
        "star": "Star Tag",
        "heart": "Heart Tag",
        "bell": "Bell Tag"
      },
      "hint": "Think about the order they were placed on gifts: star first, then heart, then bell.",
      "solved": "The handwriting matches mom's note on the fridge. Interesting...",
      "keepQuiet": "Keep this to yourself for now",
      "askParent": "Ask a leading question at dinner",
      "continue": "Continue"
    },
    "s2": {
      "title": "Tooth Tradition",
      "body": "In your bedroom, you find two notes — one from the 'Tooth Fairy' and one from a parent. Compare the letters.",
      "prompt": "Match the letters that look the same across both notes:",
      "lettersFound": "Letters matched",
      "keepNote": "Keep the note as evidence",
      "leaveNote": "Leave it be for now",
      "solved": "The same handwriting appears on both notes. A pattern is emerging."
    },
    "s3": {
      "title": "Proof Moment",
      "body": "You overhear muffled voices from the kitchen. There's a receipt on the counter and a gift bag in the closet. What do you believe?",
      "prompt": "The evidence is piling up. How do you feel about what you're discovering?",
      "confrontNow": "Confront your parents now — you want the truth",
      "saveLater": "Save the discovery for later — you're not in a hurry",
      "gentleNote": "Traditions are a way families show love. The magic lives in kindness.",
      "continue": "Continue to the Rite"
    },
    "epilogue": {
      "title": "The Rite of Discovery",
      "body": "Your parents sit down with you. They smile warmly. \"We knew this day would come,\" they say. \"Now you're part of the tradition — the helpers who keep the magic alive for younger ones.\"",
      "proud": "You feel proud. You're in on the secret now — a rite of passage.",
      "cozy": "You feel cozy. The magic didn't disappear — it just changed shape.",
      "badge": "Helper Badge earned! You're now part of the circle of kindness.",
      "restart": "Restart Adventure",
      "viewOutro": "View Outro"
    },
    "outro": {
      "title": "Discovery Complete",
      "body": "You've completed your Rite of Discovery. Every family tradition is a choice to create wonder. Now you can be a wonder-maker too.",
      "replay": "Play again from the start",
      "otherBranch": "Try the other S3 branch",
      "gentleToggle": "Toggle Gentle Mode for next run",
      "ngPlus": "New Game+: Mentor Mini"
    }
  },
  "snake": {
    "title": "Snake",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "sysdisc": {
    "intro": {
      "title": "Systems Discovery",
      "p1": "Systems are all around us.",
      "p2": "Explore how parts work together to create a whole.",
      "cta": "Begin",
      "skip": "Skip intro"
    },
    "b1": {
      "title": "Closing the Loop",
      "prompt": "Complete the cycle by activating steps in order.",
      "hint": "Gentle hint: Kitchen -> Compost -> Soil -> Herbs.",
      "steps": {
        "kitchen": "Kitchen Scraps",
        "compost": "Compost Bin",
        "soil": "Rich Soil",
        "herbs": "Fresh Herbs"
      },
      "continue": "Continue"
    },
    "b2": {
      "title": "Route Planning",
      "prompt": "Choose your primary transport mode.",
      "busFirst": "Bus focus",
      "bikeFirst": "Bike focus"
    },
    "b3": {
      "title": "Waste Sorting",
      "prompt": "Sort the items into the correct bins.",
      "hintsOn": "Hints: ON",
      "hintsOff": "Hints: OFF",
      "hintDetail": "Organic goes to green, plastic to blue, paper to yellow.",
      "items": {
        "banana": "Banana Peel",
        "bottle": "Plastic Bottle",
        "paper": "Newspaper"
      },
      "reveal": "Finish Episode"
    },
    "wrap": {
      "title": "Systems Explored",
      "done": "You've successfully mapped the core systems.",
      "b1": "Loop",
      "b2": "Plan",
      "b3": "Sorting"
    },
    "outro": {
      "title": "Discovery Complete",
      "p1": "You have a better understanding of how these systems interact.",
      "recap": "Final choices",
      "replay": "Replay Episode",
      "altPlan": "Try alternative plan",
      "toggleHints": "Toggle hints"
    },
    "bod": {
      "common": {
        "continue": "Continue",
        "reveal": "Finish trial",
        "home": "Back to Hub",
        "replay": "Replay"
      },
      "breath": {
        "intro": {
          "title": "Body Systems: Breath",
          "p1": "Oxygen is the fuel for every cell in your body.",
          "cta": "Start simulation",
          "skip": "Skip intro"
        },
        "bb1": {
          "title": "Oxygen Flow",
          "prompt": "Connect the airway to restore oxygen flow to the tissues."
        },
        "bb2": {
          "title": "Gas Exchange",
          "prompt": "Monitor homeostasis as gases move across membranes."
        },
        "bb3": {
          "title": "Regulation",
          "prompt": "Maintain balance under changing conditions."
        },
        "outro": {
          "title": "Respiration Restored",
          "p1": "The system is stable and oxygenating efficiently."
        }
      },
      "fuel": {
        "intro": {
          "title": "Body Systems: Fuel",
          "p1": "Nutrients must be broken down and transported.",
          "cta": "Start simulation",
          "skip": "Skip intro"
        },
        "bf1": {
          "title": "Nutrient Matching",
          "prompt": "Match each food to the primary nutrient it provides.",
          "foods": {
            "pasta": "Pasta",
            "chicken": "Chicken",
            "avocado": "Avocado"
          },
          "nutrients": {
            "glucose": "Glucose (Carbs)",
            "protein": "Protein",
            "fats": "Healthy Fats"
          },
          "match": "Match",
          "matched": "Matched!",
          "solved": "All nutrients matched!"
        },
        "bf2": {
          "title": "Absorption",
          "prompt": "Transport nutrients into the bloodstream."
        },
        "bf3": {
          "title": "Storage",
          "prompt": "Manage energy reserves for future use."
        },
        "outro": {
          "title": "Fueling Complete",
          "p1": "The body has the energy it needs to function."
        }
      },
      "move": {
        "intro": {
          "title": "Body Systems: Move",
          "p1": "Muscles and bones work in concert.",
          "cta": "Start simulation",
          "skip": "Skip intro"
        },
        "bm1": {
          "title": "Contraction",
          "prompt": "Coordinate muscle fibers for precise movement."
        },
        "bm2": {
          "title": "Support",
          "prompt": "Leverage the skeletal structure for strength."
        },
        "bm3": {
          "title": "Locomotion",
          "prompt": "Achieve complex movement patterns."
        },
        "outro": {
          "title": "Movement Mastered",
          "p1": "The system is agile and responsive."
        }
      },
      "signal": {
        "intro": {
          "title": "Body Systems: Signal & Defend",
          "p1": "Rapid communication and robust protection.",
          "cta": "Start simulation",
          "skip": "Skip intro"
        },
        "bsd1": {
          "title": "Transmission",
          "prompt": "Send electrical signals across neural pathways."
        },
        "bsd2": {
          "title": "Immunity",
          "prompt": "Identify and neutralize external threats."
        },
        "bsd3": {
          "title": "Reaction",
          "prompt": "Coordinate systemic responses to stimuli."
        },
        "outro": {
          "title": "Signals Clear",
          "p1": "Communication is fast and the body is protected."
        }
      },
      "space": {
        "intro": {
          "title": "Space Pack — Solar System",
          "p1": "Explore the orbits and connections between celestial bodies.",
          "p2": "How do planets, moons, and stars connect across vast distances?",
          "cta": "Launch",
          "skip": "Skip intro"
        },
        "s1": {
          "title": "Orbits & Periods",
          "prompt": "Connect the celestial bodies in their orbital paths. Rotate tiles and open valves to complete the connections.",
          "hint": "The Sun connects to Mercury, then Venus, then Earth, then Mars.",
          "bodies": {
            "sun": "Sun",
            "mercury": "Mercury",
            "venus": "Venus",
            "earth": "Earth",
            "mars": "Mars"
          },
          "rotate": "Rotate",
          "openValve": "Open orbit path",
          "solved": "Orbital paths connected! The solar system flows.",
          "continue": "Continue"
        },
        "s2": {
          "title": "Light & Shadows",
          "prompt": "Match each planet to its correct shadow size and shape.",
          "hint": "Mercury is the smallest, Earth is medium, Jupiter is the largest.",
          "planets": "Planets",
          "shadows": "Shadows",
          "planetLabels": {
            "mercury": "Mercury",
            "earth": "Earth",
            "jupiter": "Jupiter"
          },
          "shadowLabels": {
            "small": "Small",
            "medium": "Medium",
            "large": "Large"
          },
          "matched": "Matched",
          "solved": "All planets matched correctly! The shadow puzzle reveals a hidden mechanism."
        },
        "s3": {
          "title": "Habitable Clues",
          "prompt": "Sort each planet into habitable or non-habitable based on its characteristics.",
          "hint": "Earth and Mars are in the habitable zone. Jupiter and Venus are not.",
          "planets": "Planets",
          "planetLabels": {
            "earth": "Earth",
            "mars": "Mars",
            "jupiter": "Jupiter",
            "venus": "Venus"
          },
          "habitable": "Habitable",
          "notHabitable": "Not Habitable",
          "habitableShort": "HAB",
          "notHabitableShort": "NOT",
          "status": "Status",
          "habitableLabel": "Habitable",
          "notHabitableLabel": "Not Habitable",
          "solved": "All planets sorted correctly! You understand which worlds could support life.",
          "reset": "Reset"
        },
        "wrap": {
          "title": "Space Explored",
          "done": "You've mapped the inner solar system.",
          "badge": "Astronomer badge earned!"
        },
        "outro": {
          "title": "Space Journey Complete",
          "p1": "The solar system's rhythms are now familiar. Each orbit tells a story of gravity and time.",
          "replay": "Replay Space Pack",
          "home": "Back to Hub"
        }
      },
      "grow": {
        "intro": {
          "title": "Body Systems: Grow",
          "p1": "Cells divide and specialize over time.",
          "cta": "Start simulation",
          "skip": "Skip intro"
        },
        "bg1": {
          "title": "Mitosis",
          "prompt": "Guide cellular replication for growth and repair."
        },
        "bg2": {
          "title": "Differentiation",
          "prompt": "Specialized cells form tissues and organs."
        },
        "bg3": {
          "title": "Maturity",
          "prompt": "Reach optimal systemic complexity."
        },
        "outro": {
          "title": "Growth Sustained",
          "p1": "The system has developed according to its blueprint."
        }
      }
    },
    "ocean": {
      "intro": {
        "title": "Ocean Pack — Deep Blue",
        "p1": "Dive into the ocean's layered world — from sunlit shallows to the dark depths.",
        "p2": "How do currents, light, and life interconnect beneath the waves?",
        "cta": "Dive In",
        "skip": "Skip intro"
      },
      "o1": {
        "title": "Ocean Layers",
        "prompt": "Sort ocean life into the correct depth zones based on where they live.",
        "hint": "Sunlit zone (0-200m): coral, plankton. Twilight (200-1000m): lanternfish. Midnight (1000-4000m): anglerfish. Abyss (4000m+): tube worms.",
        "zones": {
          "sunlit": "Sunlit (Epipelagic)",
          "twilight": "Twilight (Mesopelagic)",
          "midnight": "Midnight (Bathypelagic)",
          "abyss": "Abyss (Abyssopelagic)"
        },
        "creatures": {
          "coral": "Coral Reef",
          "plankton": "Phytoplankton",
          "lanternfish": "Lanternfish",
          "anglerfish": "Anglerfish",
          "tubeworm": "Tube Worm",
          "giantsquid": "Giant Squid"
        },
        "sorted": "All creatures sorted correctly!",
        "reset": "Reset",
        "continue": "Continue"
      },
      "o2": {
        "title": "Currents & Climate",
        "prompt": "Connect the global ocean currents to complete the conveyor belt circulation.",
        "hint": "Warm surface currents flow poleward. Cold deep currents flow back toward the equator.",
        "currents": {
          "gulf": "Gulf Stream (Warm)",
          "kuroshio": "Kuroshio (Warm)",
          "antarctic": "Antarctic Circumpolar (Cold)",
          "california": "California Current (Cold)"
        },
        "rotate": "Rotate",
        "openValve": "Open current gate",
        "solved": "Ocean conveyor belt complete! The global circulation flows.",
        "continue": "Continue"
      },
      "o3": {
        "title": "Deep Signals",
        "prompt": "Match each marine creature to its unique communication method.",
        "hint": "Whales sing, dolphins click, pistol shrimp snap, bioluminescent fish flash.",
        "signals": {
          "whale": "Whale Song",
          "dolphin": "Dolphin Clicks",
          "shrimp": "Pistol Shrimp Snap",
          "bioglow": "Bioluminescent Flash"
        },
        "creatureLabels": {
          "humpback": "Humpback Whale",
          "bottlenose": "Bottlenose Dolphin",
          "pistol": "Pistol Shrimp",
          "anglerfish": "Deep-sea Anglerfish"
        },
        "matched": "Matched",
        "solved": "All creatures matched correctly! You understand how the deep ocean communicates.",
        "reset": "Reset"
      },
      "wrap": {
        "title": "Ocean Explored",
        "done": "You've navigated the ocean from surface to abyss.",
        "badge": "Oceanographer badge earned!"
      },
      "outro": {
        "title": "Ocean Journey Complete",
        "p1": "The ocean's rhythms are now familiar. From sunlit coral to hadal trenches, every depth tells a story.",
        "replay": "Replay Ocean Pack",
        "home": "Back to Hub"
      }
    }
  },
  "tower-defense": {
    "title": "Tower Defense",
    "hud": {
      "score": "Score",
      "lives": "Lives",
      "level": "Level",
      "moves": "Moves",
      "pairs": "Pairs",
      "wave": "Wave",
      "money": "Money"
    },
    "gameOver": {
      "title": "Game Over",
      "restart": "Play Again",
      "finalScore": "Final Score"
    },
    "win": {
      "title": "Congratulations",
      "message": "You did it!",
      "playAgain": "Play Again"
    }
  },
  "tme": {
    "intro": {
      "title": "Toymaker Escape",
      "prompt": "Choose your approach.",
      "gears": "Gears",
      "music": "Music"
    },
    "intro2": {
      "title": "Toymaker Escape",
      "p1": "A late evening at the atelier.",
      "p2": "Something is amiss…",
      "cta": "Begin",
      "skip": "Skip intro"
    },
    "e1": {
      "title": "Toymaker Escape — Episode 1",
      "body": "A quiet workshop. Clues hide in plain sight.",
      "keypad": {
        "hint": "A clue in the room seems to suggest the order... study the toys on the shelf.",
        "clear": "Clear",
        "submit": "Submit",
        "input": "Input:",
        "unlocked": "Unlocked"
      },
      "gears": {
        "instruction": "Adjust the gears to achieve a 1:3 ratio (output = 1/3 of input speed)."
      },
      "panel": {
        "title": "Panel (wires & pipes)",
        "wiresHint": "Connect without crossings.",
        "wiresSolved": "Wires: Solved",
        "wiresAvoid": "Avoid crossings.",
        "pipesHint": "Rotate tiles; valve must be open.",
        "pipesSolved": "Pipes: Solved",
        "pipesNotSolved": "Pipes: Not solved",
        "rotate00": "Rotate (0,0)",
        "rotate20": "Rotate (2,0)",
        "openValve": "Open valve"
      },
      "latch": {
        "hint": "Hint: long‑press then drag on the scuff to reveal a latch.",
        "revealed": "Latch revealed."
      },
      "medal": {
        "label": "Medal:",
        "gold": "gold",
        "silver": "silver",
        "bronze": "bronze"
      }
    },
    "e2": {
      "filing": {
        "title": "Filing Logic",
        "prompt": "Sort each toy into the correct cabinet based on the clues.",
        "hint": "Dolls go to Cabinet A, cars to Cabinet B, puzzles to Cabinet C.",
        "items": {
          "doll": "Porcelain Doll",
          "car": "Wind-up Car",
          "puzzle": "Jigsaw Puzzle"
        },
        "cabinets": {
          "a": "Cabinet A (Dolls)",
          "b": "Cabinet B (Vehicles)",
          "c": "Cabinet C (Puzzles)"
        },
        "sorted": "All toys sorted correctly! The filing-cabinet key turns.",
        "reset": "Reset"
      },
      "shadow": {
        "title": "Shadow Safe",
        "prompt": "Align the shapes to cast the correct shadow pattern on the wall.",
        "hint": "Drag each shape until the combined shadow matches the safe's keyhole pattern.",
        "solved": "The shadow aligns perfectly. The safe clicks open.",
        "reset": "Reset positions"
      },
      "gearwall": {
        "title": "Mechanical Gear Wall",
        "prompt": "A massive wall of interlocking gears blocks the passage. Align the outer ring to the inner ring to unlock it.",
        "instruction": "Adjust the gear teeth so the output gear spins at exactly half the speed of the input.",
        "inner": "Inner",
        "idler": "Idler",
        "outer": "Outer",
        "confirm": "Confirm gears",
        "solved": "The gear wall grinds to a halt! A hidden passage opens."
      },
      "brokentoys": {
        "title": "Broken Toy Workbench",
        "prompt": "The toymaker's workbench is cluttered with broken toys. Three toys need repairing to reveal the next clue.",
        "body": "Each broken toy has a missing piece. Find the right match to restore them.",
        "gears": "Broken Gear Bear",
        "musicbox": "Silent Music Box",
        "puppet": "Tangled Marionette",
        "pieces": {
          "cog": "Brass Cog",
          "cylinder": "Music Cylinder",
          "strings": "Replacement Strings"
        },
        "solved": "All toys repaired! A hidden drawer slides open revealing a brass key.",
        "reset": "Reset"
      },
      "wrap": {
        "title": "Episode 2 Complete",
        "body": "The office secrets are revealed. You found the commissioner's notes.",
        "medalEarned": "Medal earned: File Clerk",
        "continueE3": "Continue to Episode 3",
        "restart": "Restart"
      }
    },
    "e3": {
      "intro": {
        "title": "Apartment Mystery",
        "body": "You arrive at your own apartment. Something feels off. The commissioner left clues here — but why YOUR apartment?"
      },
      "locks": {
        "title": "Environmental Locks",
        "prompt": "Trigger the objects in the right sequence: water, sunlight, soil.",
        "water": "Water",
        "sunlight": "Sunlight",
        "soil": "Soil",
        "progress": "Progress",
        "solved": "Locks sequence solved!",
        "continueToPhotos": "Continue to photo wall"
      },
      "photos": {
        "title": "Photo Memory Wall",
        "prompt": "Three photos are pinned to the wall. Identify the two that are connected.",
        "toymaker": "Toymaker",
        "partner": "Partner",
        "stranger": "Stranger",
        "found": "You found the connection! The commissioner and the toymaker share a link.",
        "continueToAnagram": "Continue to fridge"
      },
      "anagram": {
        "title": "Fridge Anagram",
        "prompt": "The fridge magnets spell a scrambled word. Rearrange them to unlock the cool storage.",
        "submit": "Submit",
        "solved": "Anagram solved!",
        "attempts": "Attempts"
      },
      "toymakerReveal": {
        "title": "The Toymaker's Studio",
        "body": "Behind the fridge, a hidden door slides open. You step into the toymaker's secret studio. The toymaker sits at a bench, smiling.",
        "dialogue": "The toymaker looks up. \"I was wondering when you'd figure it out. You built this puzzle for yourself, you know. The question is: do you remember why?\"",
        "remember": "I remember everything now.",
        "confused": "I don't understand... tell me.",
        "continue": "Continue"
      },
      "finalEscape": {
        "title": "The Final Lock",
        "prompt": "One last puzzle stands between you and freedom. A complex locking mechanism requires the correct sequence of turns.",
        "instruction": "Turn the dials in the correct order. The toymaker's voice guides you: \"Left... more left... now right...\"",
        "turnLeft": "Turn Left",
        "turnRight": "Turn Right",
        "pull": "Pull Handle",
        "solved": "The final lock clicks open. The front door swings wide. You step out into the morning light, the puzzle complete.",
        "progress": "Step"
      },
      "wrap": {
        "title": "Episode 3 Complete",
        "body": "The apartment mystery is solved. The commissioner WAS the toymaker — you created this puzzle for yourself.",
        "medalEarned": "Medal earned: Toymaker's Apprentice"
      }
    },
    "sound": {
      "bg": {
        "workshop": "/sounds/tme-workshop-ambient.mp3",
        "office": "/sounds/tme-office-ambient.mp3",
        "apartment": "/sounds/tme-apartment-ambient.mp3"
      }
    }
  }
};
const frGames = {
  "breakout": {
    "title": "Casse-briques",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "bubble-pop": {
    "title": "Bulles",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "checkers": {
    "title": "Dames",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "chess": {
    "title": "Échecs",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "chronoshift": {
    "title": "Labyrinthe ChronoShift",
    "score": "Score",
    "rewinds": "Retours",
    "crystals": "Cristaux",
    "rewinding": "Retour en cours...",
    "controls": "WASD/Flèches : Bouger  |  R : Retour  |  E : Déplacer mur",
    "win": "Labyrinthe terminé !",
    "lose": "Partie terminée",
    "finalScore": "Score final",
    "playAgain": "Rejouer"
  },
  "timeclone": {
    "title": "Puzzle Clone Temporel",
    "score": "Score",
    "level": "Niveau",
    "phase": "Phase",
    "explore": "Explorer",
    "recording": "Enregistrement des déplacements",
    "cloneActive": "Clone actif",
    "controls": "WASD/Flèches : Bouger | Atteignez la porte temporelle pour enregistrer | Le clone répète votre chemin",
    "win": "Harmonie temporelle atteinte !",
    "finalScore": "Score final",
    "retry": "Réessayer",
    "nextLevel": "Prochain puzzle",
    "playAgain": "Rejouer",
    "you": "Vous",
    "clone": "Clone temporel",
    "yourExit": "Votre sortie",
    "cloneExit": "Sortie du clone",
    "timegate": "Porte temporelle",
    "switch": "Dalle interrupteur"
  },
  "elementalconflux": {
    "title": "Confluence élémentaire",
    "fire": "Feu",
    "water": "Eau",
    "earth": "Terre",
    "air": "Air",
    "fAbility": "Fondre glace",
    "qAbility": "Éteindre feu",
    "gAbility": "Pilier",
    "spaceAbility": "Pousser",
    "active": "actif",
    "controls": "WASD/Flèches : Bouger | Tab/1-4 : Changer | F : Feu | Q : Eau | G : Terre | Espace : Air",
    "level": "Niveau",
    "moves": "Coups",
    "time": "Temps",
    "complete": "Tous les éléments unis !",
    "reached": "Atteint",
    "pending": "En attente",
    "finalScore": "Score",
    "restart": "Recommencer",
    "nextLevel": "Niveau suivant",
    "playAgain": "Rejouer"
  },
  "memory": {
    "title": "Mémoire",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "platformer": {
    "title": "Plateforme",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "quantumarchitect": {
    "title": "Architecte quantique",
    "score": "Score",
    "observations": "Observations",
    "quantumProb": "Probabilité :",
    "controls": "WASD/Flèches pour bouger | Espace pour observer | Ramassez les clés pour ouvrir les portes",
    "begin": "Commencer l'expérience",
    "level": "Niveau",
    "win": "Fonction d'onde résolue !",
    "finalScore": "Score final",
    "totalObs": "Total des observations",
    "newExperiment": "Nouvelle expérience",
    "subtitle": "Manipulez les états quantiques, ramassez les clés et naviguez les plateformes intriquées.",
    "keys": "Clés",
    "gateLocked": "Verrouillé",
    "gateOpen": "Ouvert",
    "entangled": "Intriqué",
    "bias": "Biais"
  },
  "rod": {
    "intro": {
      "title": "Rite of Discovery — Intro",
      "p1": "Une tradition familiale. Un choix discret. Ce soir, cela commence.",
      "p2": "Soyez attentif aux détails — ils peuvent guider vos choix.",
      "cta": "Commencer",
      "skip": "Passer l'intro"
    },
    "hallway": {
      "title": "Le couloir sombre",
      "body": "Une lourde porte métallique bloque votre chemin. Un pavé numérique luit faiblement.",
      "goBack": "Retourner"
    },
    "keypad": {
      "title": "Serrure à code",
      "body": "Entrez le code à 4 chiffres trouvé sur le vieux parchemin.",
      "back": "Retour",
      "input": "Entrée :",
      "clear": "Effacer",
      "submit": "Valider",
      "unlocked": "Déverrouillé"
    },
    "wires": {
      "title": "Panneau de maintenance",
      "body": "Des fils dénudés bourdonnent d'énergie. Connectez-les correctement pour restaurer la lumière.",
      "back": "Retour",
      "solved": "Fils : Résolu",
      "connect": "Connecter"
    },
    "chamber": {
      "title": "La chambre intérieure",
      "body": "L'air est immobile ici. Vous avez passé la première épreuve.",
      "restart": "Recommencer"
    },
    "s1": {
      "title": "La veille au soir",
      "body": "Le salon est calme. Du papier d'emballage et des étiquettes sont éparpillés sur la table. Une étiquette s'est déchirée — reassemblez-la.",
      "prompt": "Assemblez les étiquettes magiques dans le bon ordre :",
      "tags": {
        "star": "Étiquette étoile",
        "heart": "Étiquette cœur",
        "bell": "Étiquette cloche"
      },
      "hint": "Pensez à l'ordre dans lequel elles ont été placées sur les cadeaux : étoile d'abord, puis cœur, puis cloche.",
      "solved": "L'écriture correspond à celle de la note de maman sur le frigo. Intéressant...",
      "keepQuiet": "Garder ça pour toi pour l'instant",
      "askParent": "Poser une question subtile au souper",
      "continue": "Continuer"
    },
    "s2": {
      "title": "La tradition de la dent",
      "body": "Dans ta chambre, tu trouves deux notes — une de la « Fée des dents » et une d'un parent. Compare les lettres.",
      "prompt": "Associe les lettres qui se ressemblent sur les deux notes :",
      "lettersFound": "Lettres associées",
      "keepNote": "Garder la note comme preuve",
      "leaveNote": "Laisser ça de côté pour l'instant",
      "solved": "La même écriture apparaît sur les deux notes. Un motif se dessine."
    },
    "s3": {
      "title": "Le moment de vérité",
      "body": "Tu entends des voix étouffées depuis la cuisine. Il y a un reçu sur le comptoir et un sac-cadeau dans le placard. Que crois-tu ?",
      "prompt": "Les preuves s'accumulent. Comment te sens-tu face à cette découverte ?",
      "confrontNow": "Confronter tes parents maintenant — tu veux la vérité",
      "saveLater": "Garder la découverte pour plus tard — tu n'es pas pressé",
      "gentleNote": "Les traditions sont une façon pour les familles de montrer leur amour. La magie vit dans la bienveillance.",
      "continue": "Continuer vers le Rite"
    },
    "epilogue": {
      "title": "Le rite de découverte",
      "body": "Tes parents s'assoient avec toi. Ils sourient chaleureusement. « Nous savions que ce jour viendrait, » disent-ils. « Maintenant tu fais partie de la tradition — les aides qui gardent la magie vivante pour les plus jeunes. »",
      "proud": "Tu te sens fier. Tu es dans le secret maintenant — un rite de passage.",
      "cozy": "Tu te sens bien. La magie n'a pas disparu — elle a juste changé de forme.",
      "badge": "Badge d'Aide gagné ! Tu fais maintenant partie du cercle de la bienveillance.",
      "restart": "Recommencer l'aventure",
      "viewOutro": "Voir la conclusion"
    },
    "outro": {
      "title": "Découverte terminée",
      "body": "Tu as complété ton Rite de Découverte. Chaque tradition familiale est un choix de créer de l'émerveillement. Maintenant tu peux être un créateur de merveilles aussi.",
      "replay": "Rejouer depuis le début",
      "otherBranch": "Essayer l'autre branche de S3",
      "gentleToggle": "Activer le mode doux pour la prochaine partie",
      "ngPlus": "Nouvelle Partie+ : Mentor Mini"
    }
  },
  "snake": {
    "title": "Serpent",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "sysdisc": {
    "intro": {
      "title": "Systems Discovery",
      "p1": "Les systèmes sont tout autour de nous.",
      "p2": "Découvrez comment les parties travaillent ensemble pour former un tout.",
      "cta": "Commencer",
      "skip": "Passer l'intro"
    },
    "b1": {
      "title": "Boucler la boucle",
      "prompt": "Complétez le cycle en activant les étapes dans l'ordre.",
      "hint": "Indice : Cuisine -> Compost -> Terreau -> Herbes.",
      "steps": {
        "kitchen": "Restes de cuisine",
        "compost": "Bac à compost",
        "soil": "Terreau riche",
        "herbs": "Herbes fraîches"
      },
      "continue": "Continuer"
    },
    "b2": {
      "title": "Planification d'itinéraire",
      "prompt": "Choisissez votre mode de transport principal.",
      "busFirst": "Priorité bus",
      "bikeFirst": "Priorité vélo"
    },
    "b3": {
      "title": "Tri des déchets",
      "prompt": "Triez les articles dans les bons bacs.",
      "hintsOn": "Indices : OUI",
      "hintsOff": "Indices : NON",
      "hintDetail": "L'organique va dans le vert, le plastique dans le bleu, le papier dans le jaune.",
      "items": {
        "banana": "Peau de banane",
        "bottle": "Bouteille en plastique",
        "paper": "Journal"
      },
      "reveal": "Terminer l'épisode"
    },
    "wrap": {
      "title": "Systèmes explorés",
      "done": "Vous avez cartographié avec succès les systèmes de base.",
      "b1": "Boucle",
      "b2": "Plan",
      "b3": "Tri"
    },
    "outro": {
      "title": "Découverte terminée",
      "p1": "Vous comprenez mieux comment ces systèmes interagissent.",
      "recap": "Choix finaux",
      "replay": "Rejouer l'épisode",
      "altPlan": "Essayer l'autre plan",
      "toggleHints": "Afficher/masquer indices"
    },
    "bod": {
      "common": {
        "continue": "Continuer",
        "reveal": "Terminer l'épreuve",
        "home": "Retour au Hub",
        "replay": "Rejouer"
      },
      "breath": {
        "intro": {
          "title": "Systèmes du corps : Souffle",
          "p1": "L'oxygène est le carburant de chaque cellule de votre corps.",
          "cta": "Lancer simulation",
          "skip": "Passer l'intro"
        },
        "bb1": {
          "title": "Flux d'oxygène",
          "prompt": "Reliez les voies respiratoires pour restaurer le flux d'oxygène vers les tissus."
        },
        "bb2": {
          "title": "Échange gazeux",
          "prompt": "Surveillez l'homéostasie pendant que les gaz traversent les membranes."
        },
        "bb3": {
          "title": "Régulation",
          "prompt": "Maintenez l'équilibre dans des conditions changeantes."
        },
        "outro": {
          "title": "Respiration restaurée",
          "p1": "Le système est stable et l'oxygénation est efficace."
        }
      },
      "fuel": {
        "intro": {
          "title": "Systèmes du corps : Énergie",
          "p1": "Les nutriments doivent être décomposés et transportés.",
          "cta": "Lancer simulation",
          "skip": "Passer l'intro"
        },
        "bf1": {
          "title": "Association de nutriments",
          "prompt": "Associez chaque aliment au nutriment principal qu'il fournit.",
          "foods": {
            "pasta": "Pâtes",
            "chicken": "Poulet",
            "avocado": "Avocat"
          },
          "nutrients": {
            "glucose": "Glucose (Glucides)",
            "protein": "Protéines",
            "fats": "Gras sains"
          },
          "match": "Associer",
          "matched": "Associé !",
          "solved": "Tous les nutriments associés !"
        },
        "bf2": {
          "title": "Absorption",
          "prompt": "Transportez les nutriments dans le sang."
        },
        "bf3": {
          "title": "Stockage",
          "prompt": "Gérez les réserves d'énergie pour une utilisation future."
        },
        "outro": {
          "title": "Alimentation terminée",
          "p1": "Le corps a l'énergie dont il a besoin pour fonctionner."
        }
      },
      "move": {
        "intro": {
          "title": "Systèmes du corps : Mouvement",
          "p1": "Les muscles et les os travaillent de concert.",
          "cta": "Lancer simulation",
          "skip": "Passer l'intro"
        },
        "bm1": {
          "title": "Contraction",
          "prompt": "Coordonnez les fibres musculaires pour un mouvement précis."
        },
        "bm2": {
          "title": "Soutien",
          "prompt": "Exploitez la structure squelettique pour la force."
        },
        "bm3": {
          "title": "Locomotion",
          "prompt": "Réalisez des schémas de mouvement complexes."
        },
        "outro": {
          "title": "Mouvement maîtrisé",
          "p1": "Le système est agile et réactif."
        }
      },
      "signal": {
        "intro": {
          "title": "Systèmes du corps : Signal & Défense",
          "p1": "Communication rapide et protection robuste.",
          "cta": "Lancer simulation",
          "skip": "Passer l'intro"
        },
        "bsd1": {
          "title": "Transmission",
          "prompt": "Envoyez des signals électriques via les voies neuronales."
        },
        "bsd2": {
          "title": "Immunité",
          "prompt": "Identifiez et neutralisez les menaces extérieures."
        },
        "bsd3": {
          "title": "Réaction",
          "prompt": "Coordonnez les réponses systémiques aux stimuli."
        },
        "outro": {
          "title": "Signaux clairs",
          "p1": "La communication est rapide et le corps est protégé."
        }
      },
      "space": {
        "intro": {
          "title": "Pack Espace — Système solaire",
          "p1": "Explorez les orbites et les connexions entre les corps célestes.",
          "p2": "Comment les planètes, les lunes et les étoiles se connectent-elles à travers de vastes distances ?",
          "cta": "Lancer",
          "skip": "Passer l'intro"
        },
        "s1": {
          "title": "Orbites et périodes",
          "prompt": "Reliez les corps célestes dans leurs trajectoires orbitales. Faites pivoter les tuiles et ouvrez les vannes pour compléter les connexions.",
          "hint": "Le Soleil se connecte à Mercure, puis Vénus, puis la Terre, puis Mars.",
          "bodies": {
            "sun": "Soleil",
            "mercury": "Mercure",
            "venus": "Vénus",
            "earth": "Terre",
            "mars": "Mars"
          },
          "rotate": "Pivoter",
          "openValve": "Ouvrir le chemin orbital",
          "solved": "Trajectoires orbitales connectées ! Le système solaire circule.",
          "continue": "Continuer"
        },
        "s2": {
          "title": "Lumière et ombres",
          "prompt": "Associez chaque planète à la bonne taille et forme d'ombre.",
          "hint": "Mercure est la plus petite, la Terre est moyenne, Jupiter est la plus grande.",
          "planets": "Planètes",
          "shadows": "Ombres",
          "planetLabels": {
            "mercury": "Mercure",
            "earth": "Terre",
            "jupiter": "Jupiter"
          },
          "shadowLabels": {
            "small": "Petite",
            "medium": "Moyenne",
            "large": "Grande"
          },
          "matched": "Associées",
          "solved": "Toutes les planètes associées correctement! Le puzzle d'ombres révèle un mécanisme caché."
        },
        "s3": {
          "title": "Indices habitables",
          "prompt": "Classez chaque planète comme habitable ou non habitable selon ses caractéristiques.",
          "hint": "La Terre et Mars sont dans la zone habitable. Jupiter et Vénus ne le sont pas.",
          "planets": "Planètes",
          "planetLabels": {
            "earth": "Terre",
            "mars": "Mars",
            "jupiter": "Jupiter",
            "venus": "Vénus"
          },
          "habitable": "Habitable",
          "notHabitable": "Non habitable",
          "habitableShort": "HAB",
          "notHabitableShort": "NON",
          "status": "Statut",
          "habitableLabel": "Habitable",
          "notHabitableLabel": "Non habitable",
          "solved": "Toutes les planètes classées correctement! Vous comprenez quels mondes pourraient soutenir la vie.",
          "reset": "Réinitialiser"
        },
        "wrap": {
          "title": "Espace exploré",
          "done": "Vous avez cartographié le système solaire interne.",
          "badge": "Badge Astronome gagné!"
        },
        "outro": {
          "title": "Voyage spatial terminé",
          "p1": "Les rythmes du système solaire vous sont maintenant familiers. Chaque orbite raconte une histoire de gravité et de temps.",
          "replay": "Rejouer le Pack Espace",
          "home": "Retour au Hub"
        }
      },
      "grow": {
        "intro": {
          "title": "Systèmes du corps : Croissance",
          "p1": "Les cellules se divisent et se spécialisent avec le temps.",
          "cta": "Lancer simulation",
          "skip": "Passer l'intro"
        },
        "bg1": {
          "title": "Mitose",
          "prompt": "Guidez la réplication cellulaire pour la croissance et la réparation."
        },
        "bg2": {
          "title": "Différenciation",
          "prompt": "Les cellules spécialisées forment des tissus et des organes."
        },
        "bg3": {
          "title": "Maturité",
          "prompt": "Atteignez une complexité systémique optimale."
        },
        "outro": {
          "title": "Croissance soutenue",
          "p1": "Le système s'est développé selon son plan."
        }
      }
    },
    "ocean": {
      "intro": {
        "title": "Pack Océan — Bleu profond",
        "p1": "Plongez dans le monde stratifié de l'océan — des hauts-fonds ensoleillés aux profondeurs obscures.",
        "p2": "Comment les courants, la lumière et la vie s'interconnectent-ils sous les vagues ?",
        "cta": "Plonger",
        "skip": "Passer l'intro"
      },
      "o1": {
        "title": "Couches océaniques",
        "prompt": "Classez la vie océanique dans les bonnes zones de profondeur selon leur habitat.",
        "hint": "Zone ensoleillée (0-200m) : corail, plancton. Crépusculaire (200-1000m) : poisson-lanterne. Minuit (1000-4000m) : baudroie. Abysses (4000m+) : vers tubicoles.",
        "zones": {
          "sunlit": "Ensoleillée (Épipélagique)",
          "twilight": "Crépusculaire (Mésopélagique)",
          "midnight": "Minuit (Bathypélagique)",
          "abyss": "Abysses (Abyssopélagique)"
        },
        "creatures": {
          "coral": "Récif corallien",
          "plankton": "Phytoplancton",
          "lanternfish": "Poisson-lanterne",
          "anglerfish": "Baudroie abyssale",
          "tubeworm": "Ver tubicole",
          "giantsquid": "Calmar géant"
        },
        "sorted": "Toutes les créatures classées correctement!",
        "reset": "Réinitialiser",
        "continue": "Continuer"
      },
      "o2": {
        "title": "Courants et climat",
        "prompt": "Reliez les courants océaniques mondiaux pour compléter la circulation du tapis roulant.",
        "hint": "Les courants chauds de surface vont vers les pôles. Les courants froids profonds retournent vers l'équateur.",
        "currents": {
          "gulf": "Gulf Stream (Chaud)",
          "kuroshio": "Kuroshio (Chaud)",
          "antarctic": "Circumpolaire antarctique (Froid)",
          "california": "Courant de Californie (Froid)"
        },
        "rotate": "Pivoter",
        "openValve": "Ouvrir la porte du courant",
        "solved": "Tapis roulant océanique complet! La circulation mondiale fonctionne.",
        "continue": "Continuer"
      },
      "o3": {
        "title": "Signaux des profondeurs",
        "prompt": "Associez chaque créature marine à sa méthode de communication unique.",
        "hint": "Les baleines chantent, les dauphins cliquent, les crevettes-pistolets claquent, les poissons bioluminescents clignotent.",
        "signals": {
          "whale": "Chant de baleine",
          "dolphin": "Clics de dauphin",
          "shrimp": "Claquement de crevette-pistolet",
          "bioglow": "Éclat bioluminescent"
        },
        "creatureLabels": {
          "humpback": "Baleine à bosse",
          "bottlenose": "Grand dauphin",
          "pistol": "Crevette-pistolet",
          "anglerfish": "Baudroie des abysses"
        },
        "matched": "Associées",
        "solved": "Toutes les créatures associées correctement! Vous comprenez comment l'océan profond communique.",
        "reset": "Réinitialiser"
      },
      "wrap": {
        "title": "Océan exploré",
        "done": "Vous avez navigué de la surface aux abysses.",
        "badge": "Badge Océanographe gagné!"
      },
      "outro": {
        "title": "Voyage océanique terminé",
        "p1": "Les rythmes de l'océan vous sont désormais familiers. Du corail ensoleillé aux fosses hadales, chaque profondeur raconte une histoire.",
        "replay": "Rejouer le Pack Océan",
        "home": "Retour au Hub"
      }
    }
  },
  "tower-defense": {
    "title": "Tour de défense",
    "hud": {
      "score": "Score",
      "lives": "Vies",
      "level": "Niveau",
      "moves": "Coups",
      "pairs": "Paires",
      "wave": "Vague",
      "money": "Argent"
    },
    "gameOver": {
      "title": "Partie terminée",
      "restart": "Rejouer",
      "finalScore": "Score final"
    },
    "win": {
      "title": "Félicitations",
      "message": "Vous avez réussi!",
      "playAgain": "Rejouer"
    }
  },
  "tme": {
    "intro": {
      "title": "Toymaker Escape",
      "prompt": "Choisissez votre approche.",
      "gears": "Engrenages",
      "music": "Musique"
    },
    "intro2": {
      "title": "Toymaker Escape",
      "p1": "Un soir tard dans l'atelier.",
      "p2": "Quelque chose cloche…",
      "cta": "Commencer",
      "skip": "Passer l'intro"
    },
    "e1": {
      "title": "Toymaker Escape — Épisode 1",
      "body": "Un atelier silencieux. Les indices se cachent à vue d'œil.",
      "keypad": {
        "hint": "Un indice dans la pièce semble suggérer l'ordre... observez les jouets sur l'étagère.",
        "clear": "Effacer",
        "submit": "Valider",
        "input": "Entrée :",
        "unlocked": "Déverrouillé"
      },
      "gears": {
        "instruction": "Réglez les engrenages pour obtenir un rapport 1:3 (sortie = 1/3 de la vitesse d'entrée)."
      },
      "panel": {
        "title": "Panneau (fils & tuyaux)",
        "wiresHint": "Reliez sans croisements.",
        "wiresSolved": "Fils : Résolu",
        "wiresAvoid": "Évitez les croisements.",
        "pipesHint": "Faites pivoter les tuiles ; la vanne doit être ouverte.",
        "pipesSolved": "Tuyaux : Résolu",
        "pipesNotSolved": "Tuyaux : Non résolu",
        "rotate00": "Pivoter (0,0)",
        "rotate20": "Pivoter (2,0)",
        "openValve": "Ouvrir la vanne"
      },
      "latch": {
        "hint": "Astuce : appui long puis glisser sur la rayure pour révéler un loquet.",
        "revealed": "Loquet révélé."
      },
      "medal": {
        "label": "Médaille :",
        "gold": "or",
        "silver": "argent",
        "bronze": "bronze"
      }
    },
    "e2": {
      "filing": {
        "title": "Logique de classement",
        "prompt": "Classez chaque jouet dans le bon classeur selon les indices.",
        "hint": "Les poupées vont dans le classeur A, les voitures dans B, les puzzles dans C.",
        "items": {
          "doll": "Poupée de porcelaine",
          "car": "Voiture à remontoir",
          "puzzle": "Casse-tête"
        },
        "cabinets": {
          "a": "Classeur A (Poupées)",
          "b": "Classeur B (Véhicules)",
          "c": "Classeur C (Puzzles)"
        },
        "sorted": "Tous les jouets sont bien classés ! La clé du classeur tourne.",
        "reset": "Réinitialiser"
      },
      "shadow": {
        "title": "Coffre d'ombre",
        "prompt": "Alignez les formes pour projeter le bon motif d'ombre sur le mur.",
        "hint": "Faites glisser chaque forme jusqu'à ce que l'ombre combinée corresponde au motif de la serrure.",
        "solved": "L'ombre s'aligne parfaitement. Le coffre s'ouvre.",
        "reset": "Réinitialiser les positions"
      },
      "gearwall": {
        "title": "Mur d'engrenages mécaniques",
        "prompt": "Un mur massif d'engrenages imbriqués bloque le passage. Alignez l'anneau extérieur sur l'anneau intérieur pour le déverrouiller.",
        "instruction": "Ajustez les dents de l'engrenage pour que l'engrenage de sortie tourne exactement à la moitié de la vitesse d'entrée.",
        "inner": "Intérieur",
        "idler": "Intermédiaire",
        "outer": "Extérieur",
        "confirm": "Valider les engrenages",
        "solved": "Le mur d'engrenages s'immobilise ! Un passage caché s'ouvre."
      },
      "brokentoys": {
        "title": "Établi des jouets cassés",
        "prompt": "L'établi du fabricant est encombré de jouets brisés. Trois jouets doivent être réparés pour révéler le prochain indice.",
        "body": "Chaque jouet cassé a une pièce manquante. Trouvez la bonne correspondance pour les restaurer.",
        "gears": "Ours à engrenage cassé",
        "musicbox": "Boîte à musique silencieuse",
        "puppet": "Marionnette emmêlée",
        "pieces": {
          "cog": "Rouage en laiton",
          "cylinder": "Cylindre musical",
          "strings": "Fils de remplacement"
        },
        "solved": "Tous les jouets réparés ! Un tiroir caché coulisse révélant une clé en laiton.",
        "reset": "Réinitialiser"
      },
      "wrap": {
        "title": "Épisode 2 terminé",
        "body": "Les secrets du bureau sont révélés. Vous avez trouvé les notes du commissaire.",
        "medalEarned": "Médaille gagnée : Commis aux archives",
        "continueE3": "Continuer vers l'Épisode 3",
        "restart": "Recommencer"
      }
    },
    "e3": {
      "intro": {
        "title": "Le Mystère de l'Appartement",
        "body": "Vous arrivez à votre propre appartement. Quelque chose semble étrange. Le commissaire a laissé des indices ici — mais pourquoi VOTRE appartement?"
      },
      "locks": {
        "title": "Verrous environnementaux",
        "prompt": "Actionnez les objets dans le bon ordre : eau, lumière, terreau.",
        "water": "Arroser",
        "sunlight": "Lumière",
        "soil": "Terreau",
        "progress": "Progression",
        "solved": "Séquence des verrous résolue!",
        "continueToPhotos": "Continuer vers le mur de photos"
      },
      "photos": {
        "title": "Mur de photos souvenir",
        "prompt": "Trois photos sont accrochées au mur. Identifiez les deux qui sont connectées.",
        "toymaker": "Fabricant",
        "partner": "Partenaire",
        "stranger": "Inconnu",
        "found": "Vous avez trouvé la connexion! Le commissaire et le fabricant partagent un lien.",
        "continueToAnagram": "Continuer vers le frigo"
      },
      "anagram": {
        "title": "Anagramme du frigo",
        "prompt": "Les aimants du frigo forment un mot mélangé. Réorganisez-les pour déverrouiller l'espace réfrigéré.",
        "submit": "Valider",
        "solved": "Anagramme résolu!",
        "attempts": "Tentatives"
      },
      "toymakerReveal": {
        "title": "Le Studio du fabricant",
        "body": "Derrière le frigo, une porte cachée s'ouvre. Vous entrez dans le studio secret du fabricant de jouets. Il est assis à un établi, souriant.",
        "dialogue": "Le fabricant lève les yeux. « Je me demandais quand tu comprendrais. Tu as construit ce puzzle pour toi-même, tu sais. La question est : te souviens-tu pourquoi ? »",
        "remember": "Je me souviens de tout maintenant.",
        "confused": "Je ne comprends pas... dites-moi.",
        "continue": "Continuer"
      },
      "finalEscape": {
        "title": "Le Verrou final",
        "prompt": "Un dernier puzzle se dresse entre vous et la liberté. Un mécanisme de verrouillage complexe nécessite la bonne séquence de rotations.",
        "instruction": "Tournez les molettes dans le bon ordre. La voix du fabricant vous guide : « Gauche... plus à gauche... maintenant droite... »",
        "turnLeft": "Tourner à gauche",
        "turnRight": "Tourner à droite",
        "pull": "Tirer la poignée",
        "solved": "Le verrou final s'ouvre. La porte d'entrée s'ouvre grand. Vous sortez dans la lumière du matin, le puzzle terminé.",
        "progress": "Étape"
      },
      "wrap": {
        "title": "Épisode 3 terminé",
        "body": "Le mystère de l'appartement est résolu. Le commissaire ÉTAIT le fabricant de jouets — vous avez créé ce casse-tête pour vous-même.",
        "medalEarned": "Médaille gagnée : Apprenti fabricant"
      }
    },
    "sound": {
      "bg": {
        "workshop": "/sounds/tme-workshop-ambient.mp3",
        "office": "/sounds/tme-office-ambient.mp3",
        "apartment": "/sounds/tme-apartment-ambient.mp3"
      }
    }
  }
};

export const gameTranslations: Record<'en' | 'fr', Record<string, any>> = {
  en: enGames,
  fr: frGames,
};
