// Shared utilities and components exports

// Core contexts
export * from "./contexts/AuthContext";
export * from "./contexts/FlagsContext";
export * from "./contexts/GameContext";
export * from "./contexts/GameSettingsContext";
export * from "./contexts/ProfileContext";
export * from "./contexts/SoundContext";
export * from "./contexts/SubscriptionContext";

// Hooks
export * from "./hooks/use-mobile";
export * from "./hooks/use-toast";

// Components - App-level
export { Carousel } from "./components/Carousel";
export { default as Footer } from "./components/Footer";
export { default as GameCard } from "./components/GameCard";
export { default as Header } from "./components/Header";
export { default as I18nInitializer } from "./components/I18nInitializer";
export { Icons } from "./components/icons";
export { default as LanguageToggle } from "./components/LanguageToggle";
export { default as LogoutButton } from "./components/LogoutButton";
export { ModeToggle } from "./components/ModeToggle";
export { default as Navbar } from "./components/Navbar";
export { PresenceBadge } from "./components/PresenceBadge";
export { default as ProtectedRoute } from "./components/ProtectedRoute";
export { default as Providers } from "./components/Providers";
export { default as SettingsPanel } from "./components/SettingsPanel";
export { default as SoundControls } from "./components/SoundControls";
export { default as SoundRootProvider } from "./components/SoundRootProvider";
export { ThemeProvider } from "./components/ThemeProvider";

// Lib utilities
export type { GameContainerProps } from "./components/GameContainer";
export { default as GameContainer } from "./components/GameContainer";
export { GameHUD } from "./components/GameHUD";
export { GameShell } from "./components/GameShell";
export * from "./components/ui/accordion";
export * from "./components/ui/alert";
export * from "./components/ui/alert-dialog";
export * from "./components/ui/aspect-ratio";
export * from "./components/ui/avatar";
export * from "./components/ui/badge";
export * from "./components/ui/breadcrumb";
export * from "./components/ui/button";
export * from "./components/ui/card";
export * from "./components/ui/carousel";
export * from "./components/ui/chart";
export * from "./components/ui/checkbox";
export * from "./components/ui/collapsible";
export * from "./components/ui/command";
export * from "./components/ui/context-menu";
export * from "./components/ui/dialog";
export * from "./components/ui/drawer";
export * from "./components/ui/dropdown-menu";
export * from "./components/ui/empty";
export * from "./components/ui/field";
export * from "./components/ui/form";
export * from "./components/ui/hover-card";
export * from "./components/ui/input";
export * from "./components/ui/input-group";
export * from "./components/ui/input-otp";
export * from "./components/ui/item";
export * from "./components/ui/kbd";
export * from "./components/ui/label";
export * from "./components/ui/menubar";
export * from "./components/ui/navigation-menu";
export * from "./components/ui/pagination";
export * from "./components/ui/popover";
export * from "./components/ui/progress";
export * from "./components/ui/radio-group";
export * from "./components/ui/resizable";export * from "./components/ui/separator";export * from "./components/ui/sidebar";export * from "./components/ui/skeleton";export * from "./components/ui/textarea";export * from "./components/ui/toaster";export * from "./components/ui/toggle";export * from "./components/ui/toggle-group";export * from "./components/ui/tooltip";
export * from "./components/ui/select";
export * from "./components/ui/switch";
export * from "./components/ui/table";
export * from "./components/ui/tabs";
export * from "./components/ui/toast";
export * from "./components/ui/use-toast";
export * from "./lib/auth";
export * from "./lib/env";
export * from "./lib/firebase";
export * from "./lib/flags";
export * from "./lib/gameProgress";
export * from "./lib/graphql/queries";
export * from "./lib/i18n";
export * from "./lib/input";
export * from "./lib/particles";
export * from "./lib/sound";
export * from "./lib/utils";
export * from "./metadata/games";
export * from "./metadata/projects";
export { GameEngine } from "./pointclick/core/Engine";
export * from "./pointclick/core/Persistence";
export { SceneManager } from "./pointclick/core/SceneManager";
export * from "./pointclick/core/SceneServices";
export * from "./pointclick/engine";
export * from "./pointclick/puzzles/gears";
export * from "./pointclick/puzzles/keypad";
export * from "./pointclick/puzzles/pipes";
export * from "./pointclick/puzzles/sequence";
export * from "./pointclick/puzzles/wires";
export { DialogueBox } from "./pointclick/react/DialogueBox";
export { InventoryBar } from "./pointclick/react/InventoryBar";
export { SceneController } from "./pointclick/react/SceneController";
export * from "./pointclick/ui/InputSequenceDetector";
export * from "./projects";
// export * from "./components/ui/resizable"; // Commented out - react-resizable-panels issue
export * from "./components/ui/scroll-area";
export * from "./components/ui/separator";
export * from "./components/ui/sheet";
export * from "./components/ui/sidebar";
export * from "./components/ui/skeleton";
export * from "./components/ui/slider";
export * from "./components/ui/sonner";
export * from "./components/ui/spinner";
export * from "./components/ui/textarea";
export * from "./components/ui/toggle";
export * from "./components/ui/toggle-group";
export * from "./components/ui/tooltip";
