-- Rollout: 003_leaderboard_moderation_and_flags_audit
-- Auto-generated by consolidate-migrations.mjs — single source of truth is 003_leaderboard_moderation_and_flags_audit.sql

\i scripts/003_leaderboard_moderation_and_flags_audit.sql
